### ISSUE TITLE
Accessing only 3 channels instead of 6

### ISSUE THREAD

**Issue by nithinpanand** [flashbac/gsv-6ToWAMP#7]
Hello,
I want to access only the first 3 channels of the sensor and I just want to publish those 3 values. I looked in the GSV6_Sim.py file and found that there is a line that describes the number of channels.

`#0b0000      # Anzahl der Kanaele -> 5 -> 1001`

 But I am not understanding the way the byte array is derived from  number of channels and other factors.

 ```
def getMesswertFrame(self):
        #0xAA        # Serial start
        #0b00        # Messwert Frame
        #0b01        # Interface -> Serial
        #0b0000      # Anzahl der Kanaele -> 5 -> 1001
        #0b10010000  # Steuerbyte / Statusbyte indikato <7>=1 <6:4>=001 (int16) <3:0>=0 (kein Error)
        #481         # Data    -> da int 16 zwei byte -> 0x00 0x01
        #0x85        # Serial ende

        # => 0xAA 0001 0001 1001 0000  0x00 0x01 0x85
        # => 0xAA    0x11      0x90    0x00 0x01 0x85

        result = bytearray([0xAA,0x11,0x90,0x00,0x01,0x85])    ###HOW THIS IS DERIVED FROM ABOVE VALUES 
        return result
```

Is it possible to select only the first 3 channels by just editing this file or is it more complicated?  Thanks.

**Comment by flashbac** [comment]
Hey nithinpanand,

the GSV6_sim Class was only for internal testing und accquire no data from the device.

You have to ignore the channel 4-6 on browser side.

**Comment by nithinpanand** [comment]
Hello flashbac,
Thanks for your reply. I did that already and ignored the values on the browser side. But this wont solve my actual issue. I want to have a better data rate by deactivating the last three channels of the GSV 6 amplifier.  And I am trying now to use GSVmulti to configure GSV6 to deactivate the unwanted 3 channels. Will this be compatible with the python code here or do I need to change serial2ws program or any other scripts to make it easily compatible?
